project_id = "jhqdrsoahbtdsxvzxees"

[functions.import-aroflo-clients]
verify_jwt = false

[functions.create-aroflo-quote]
verify_jwt = false

[functions.send-report]
verify_jwt = false

[functions.generate-site-assessment-summary]
verify_jwt = false

[functions.receipt-ocr]
verify_jwt = false

[functions.ai-estimate]
verify_jwt = false
